name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm pkg delete scripts.prepare
      - run: npm ci
      - run: npm run prepublishOnly
      - run: cp package.json ./dist
      - run: npm publish
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
